### ISSUE TITLE
Mac/Linux installation URL's throw a 404

### ISSUE THREAD

**Issue by mrjkc** [kinvolk/headlamp#119]
**Description**

When I try to access the following URL through the README.md file: (https://github.com/kinvolk/headlamp/blob/master/docs/installation/desktop/mac-installation) to install a desktop app, it gives me 404 page not gound error. Has this been moved somewhere and the links in the README file not updated?

**Comment by joaquimrocha** [comment]
Sorry. The docs are using the k8s style and have no .md extensions for links. We will be looking for a solution for this very soon, but in the meanwhile I will link to the Kinvolk Docs portal which I recommend you check: https://kinvolk.io/docs/headlamp/latest/contributing

**Comment by mrjkc** [comment]
> Sorry. The docs are using the k8s style and have no .md extensions for links. We will be looking for a solution for this very soon, but in the meanwhile I will link to the Kinvolk Docs portal which I recommend you check: https://kinvolk.io/docs/headlamp/latest/contributing

Thanks!
