### ISSUE TITLE
metrics for each node usage

### ISSUE THREAD

**Issue by maheshk245** [kinvolk/headlamp#123]
I tried to use the headlamp for my cluster. it was showing that I need to add the metrics to get the usage details of each node. But I didn't find any documentation regarding how to add the metics

**Comment by joaquimrocha** [comment]
Hi @maheshk245 . For getting metrics you will need the `metrics-server`.
It's true we don't have that documented as it something more related to Kubernetes itself than Headlamp (but I will think about adding it).

If you are running minikube, maybe check:
https://kubernetes.io/docs/tutorials/hello-minikube/

Or if you want something less automagic:
https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/#metrics-server

**Comment by joaquimrocha** [comment]
Ihave opened #124 to track this BTW. Thanks.
