### ISSUE TITLE
How to deploy headlamp in my local minikube  on windows 

### ISSUE THREAD

**Issue by PmcFizz** [kinvolk/headlamp#135]
hi This is a great project，and I want to contribute code.
but  as title  I meet trouble
I don‘t konw what is it the url `headlamp.mydeployment.io` .
Can you help me make a develop environment ？

**Comment by joaquimrocha** [comment]
@PmcFizz , the URL you mention was an example for when running in-cluster.
We're working on providing better documentation for running Headlamp on Minikube.
If you want to run it in a developer environment against a running `minikube` (i.e. minikube is configured in your `~/.kube/config`), then you can run Headlamp with the following instructions:
https://kinvolk.io/docs/headlamp/latest/development/

Let me know if this helps.

**Comment by PmcFizz** [comment]
It‘s work
