### ISSUE TITLE
Where to paste the token?

### ISSUE THREAD

**Issue by torbjornvatn** [kinvolk/headlamp#136]
In the documentation it says that you should paste the RBAC token when prompted by Headlamp, but my installation never does that. 
Is there a way to force that prompt?

**Comment by joaquimrocha** [comment]
Hi @torbjornvatn ,

When accessing Headlamp's root URL, it will show the configured contexts or skip this view if only one context is configured; then it will either show the authentication options dialog (see below) or go straight into the token prompt dialog.
![login screen](https://kinvolk.io/docs/headlamp/0.1/installation/oidc_button.png)

Notice that if you have a working client certificate defined for the context, Headlamp will try to use that (and fallback to asking for a token if it couldn't succeed using the certificates).

Can you tell me a bit more about how you are running Headlamp (in-cluster or as a desktop app, how many clusters defined)? If you give me more context on your deployment, we may be able to check whether we have an error in that layer that's failing to show you the token prompt.

Thanks in advance.

**Comment by alessiot77** [comment]
Same here, I don't get prompted to sign in. I'm fairly new to headlamp, but a few observations are:

1. introduce a path based ingress configuration
2. test it with cloud provider kubernetes environments: I'm using AKS
3. the HeadLamp daemonset log show:

*** Headlamp Server ***
  API Routers:
        localhost:4466/clusters/main/{api...} -> https://xxxxx-aks-1bf6f243.hcp.eastus2.azmk8s.io:443
2020/12/07 17:05:57 Error:  <nil>


I really like the concept and I can't wait to see this project grow. Any ideas on the above and/or how to debug this further ?

**Comment by joaquimrocha** [comment]
Hi @alessiot77 , can you see if you force the token prompt by going to https://YOUR_URL/c/main/token ?
We will try Headlamp on AKS soon to see if there is something we're missing in that flavor.

Thanks for reporting.

**Comment by joaquimrocha** [comment]
Opened #147. Closing this one.
