### ISSUE TITLE
Add a headless app mode

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/headlamp#148]
**Current situation**
Our desktop apps use Electron to run the UI and package it like a desktop app. However, this means that the user cannot use their favorite browser and browser features (like bookmarks, groups, etc.).

**Ideal future situation**
There is a way to run Headlamp's destop version using the default browser.

**Implementation options**
* All apps have a `headless` mode, which means that when they are run with this option, they will open the default browser instead of using the electron view.
* We build a new `headlamp-headless` version of the desktop app which doesn't include Electron (meaning the app is also lighter in size).

**Comment by ashu8912** [comment]
This has landed in the master branch. We can close this issue now.

**Comment by ashu8912** [comment]
@joaquimrocha
