### ISSUE TITLE
Support setting up custom baseURL

### ISSUE THREAD

**Issue by trim777** [kinvolk/headlamp#150]
**Current situation**
I'm running headlamp behind reverse proxy (nginx -> k8s-ingress -> service -> pod), that makes impossible to publish applications which don't support option which called sometimes like 'base-url' - this option allows to point the application to serve website-files on path different from ``/`` 

**Ideal future situation**
Please, implement this feature, it would be great to have it, because without it our users cannot visit app-UI without using kubectl port-forward.

**Implementation options**
It can be either ENV-variable or command-line argument for headlamp-server.

Thanks a lot for such awesome software!

**Comment by joaquimrocha** [comment]
@illume , You may be running Headlamp on minikube soon, so maybe this is something you can check.

**Comment by illume** [comment]
Hi @trim777,

support for this has been merged into main, and will be included in the new release. There's documentation in docs/installation/base-url.md which will also be on the documentation website after the next release.
