### ISSUE TITLE
Mac code signing

### ISSUE THREAD

**Issue by illume** [kinvolk/headlamp#167]
**Current situation**

The Mac app should be code signed so it can be run more easily.

**Implementation options**

https://www.electronjs.org/docs/tutorial/code-signing#code-signing

**Comment by illume** [comment]
What I tried so far with `electron-packager` linked from the electron docs, isn't quite working. It's very big for some reason (1.2GB), and doesn't make a .dmg.

Install the electron-packager:

```npm install electron-packager -g```

Find identity:

```security find-identity```

Make the signed app:

```electron-packager . "Headlamp Kubernetes UI" --platform=darwin --arch=x64 --app-bundle-id="io.kinvolk.Headlamp" --app-version="0.2.0" --build-version="0.2.100" --osx-sign.identity="939R32ZCVC" --overwrite```

**Comment by illume** [comment]
Using https://www.electron.build/code-signing I got it signing, but only with my own developer certificate.

```
make app-mac
```

<img width="741" alt="Screenshot 2021-01-15 at 09 21 37 1" src="https://user-images.githubusercontent.com/9541/104699495-1d26a880-5713-11eb-97e3-85d2bac98bbb.png">

You can confirm what it has been signed with using:
```
$ codesign -dvvv dist/mac/Headlamp.app 2> >(grep Auth)
Authority=Apple Development: Rene Dudfield (939R32ZCVC)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
```

Note, there is no "Developer ID Application" one.

There's some environment variables to control which identity and certificates it uses.
```
CSC_NAME="Kinvolk GmbH (Z3JLKXXXX)" CSC_LINK=path-to-file.pem make app-mac
```

Seems the private key is missing on my machine for the "Developer ID Application" one.
<img width="946" alt="Screenshot 2021-01-15 at 09 15 25" src="https://user-images.githubusercontent.com/9541/104698907-4d217c00-5712-11eb-8fca-8f57bd254def.png">


According to these docs: https://help.apple.com/xcode/mac/current/#/dev154b28f09 the creator of the certificate needs to export it on their mac (and then share the private file).

**Comment by joaquimrocha** [comment]
This is already done.
