### ISSUE TITLE
Create minikube addon

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/headlamp#174]
**Description**
We want users to easily try Headlamp, so we should plan adding a minikube addon.

**Comment by illume** [comment]
The docs for [making minikube addons](https://minikube.sigs.k8s.io/docs/contrib/addons/).

**Comment by joaquimrocha** [comment]
Minikube PR is here: https://github.com/kubernetes/minikube/pull/14315

**Comment by joaquimrocha** [comment]
This is done. We're just waiting for https://github.com/kubernetes/minikube/pull/14522 so we publish more info about it in our docs + blog.
