### ISSUE TITLE
old versions of docs and search engines

### ISSUE THREAD

**Issue by illume** [kinvolk/headlamp#176]
**Description**

- Search for "[headlamp documentation](https://www.google.com/search?q=headlamp+documentation)"
- Get 0.1 link
- 404

<img width="393" alt="Screenshot 2021-01-22 at 17 47 34" src="https://user-images.githubusercontent.com/9541/105519686-01ef0680-5cda-11eb-9fe9-b1f07d1e5df1.png">
<img width="921" alt="Screenshot 2021-01-22 at 17 47 41" src="https://user-images.githubusercontent.com/9541/105519691-03b8ca00-5cda-11eb-82d9-cce21fcc32a1.png">

**Impact**

Documentation isn't indexed by search engines nicely.

**Expected behavior**

Docs should perhaps have either:
- a latest version, and a version selector with a warning if you've landed on old-version-docs.
- one version of the docs which covers version differences.

**Comment by joaquimrocha** [comment]
Fixed. Thanks!
