### ISSUE TITLE
Build + distribute plugins out-of-tree

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/headlamp#18]
Right now, even if plugins are self-contained in their own folder and not importing project's modules directly, they're still being built together with the project.

In order to make the plugins really powerful, we should have them built outside of the project (out-of-tree), and imported in a different way (likely sent from the backend according to how it is configured). 
We should check out Mattermost's approach for inspiration: https://github.com/mattermost/mattermost-plugins

**Acceptance Criteria:**
- [x] Plugins are built out-of-tree
- [x] The dashboard can import them dynamically according to what the backend indicates (details TBD)

**Comment by ashu8912** [comment]
@joaquimrocha we have this in master we can close this
