### ISSUE TITLE
Log in with the choices is mistakenly skipped

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/headlamp#182]
**Description**

While testing v0.2.0 in-cluster with OIDC configured and without the user authenticated, Headlamp is failling to show the log in options (Sign-in + Token) to the user and goes straight to the token prompt.

**Impact**

Users cannot use OIDC.

**Comment by illume** [comment]
From the changes in 0.1.3 to 0.2.0, 
https://github.com/kinvolk/headlamp/compare/v0.1.3...v0.2.0

The Login Improvements PR seems a possibility: https://github.com/kinvolk/headlamp/pull/144
