### ISSUE TITLE
Allow to load plugins when running locally

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/headlamp#201]
**Current situation**
Currently we don't have a way to specify which plugins to load when Headlamp is run as a desktop app.

**Impact**
Users cannot load plugins if they are running Headlamp locally.

**Ideal future situation**
We want to allow users to use Headlamp with plugins in the desktop.

**Implementation options**
MVP: The minimal changes would be to expose the `-plugins-dir` server option. This would solve enabling the feature.

Full implementation: Ideally we'd have a menu where we allow the user to choose each plugin file or dir (which in the back would copy the file to a configuration folder). This solution may require some changes in the backend, to reload the plugins logic without a restart.

Dev bonus: We could have a "watch" option in the UI/CLI for the desktop app so that any changes to the plugins would get reloaded. So we could perhaps use this approach for plugin development if users don't want to run Headlamp from source.

**Comment by illume** [comment]
Good idea.

Some related points:
- [app.getPath(name)](https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname) for x-platform config/user folder getting. (Electron makes us a ~/.config/Headlamp/ on linux for example).
- related app [configuration](https://github.com/kinvolk/headlamp/issues/160)/preferences issue.

**Comment by joaquimrocha** [comment]
Implemented in v0.3.0.
