### ISSUE TITLE
Documentation of components and API

### ISSUE THREAD

**Issue by illume** [kinvolk/headlamp#205]
**Current situation**

For headlamp developers and plugin authors it would be useful to have more documentation of certain APIs and components.

**Impact**

Improves the developer experience.

**Ideal future situation**

- Locally inside an IDE (like vscode) documentation for relevant APIs is shown.
- Locally the storybook tool can be used to discover and develop components.
- Published online in the Kinvolk docs, people can view components and API docs.

**Implementation options**

Typedoc and Storybook can provide this.

The components (at least common) all have stories, and at least lib/k8s API is mostly documented.

**Comment by joaquimrocha** [comment]
The bulk of it is done, even if we're not covering everything 100%. Closing.
