### ISSUE TITLE
Headlamp with a base-url and OIDC

### ISSUE THREAD

**Issue by zukko78** [kinvolk/headlamp#238]
**Description**

I'd like to use in cluster deployment with - "-base-url=/headlamp" but when I press the "SIGN-IN" button I get an error - 
**Bad Request
Unregistered redirect_uri ("https://my-host.org/oidc-callback").**

**Impact**

Unreachable callback URL (e.g. **https://YOUR_URL/oidc-callback**) to Dex’s staticClient.redirectURIs

**Environment and steps to reproduce**

1. **Set-up**: 
Kubernetes 1.18.x
Headlamp in cluster deployed with settings:

        - args:
            - '-in-cluster'
            - '-plugins-dir=/headlamp/plugins'
            - '-oidc-client-id=oidc-auth-client'
            - '-base-url=/headlamp'
            - '-oidc-client-secret=xxxx'
            - >-
              -oidc-idp-issuer-url=https://oauth.my-host.org/dex
            - '-oidc-scopes=profile,email,groups'

Ingress:

  name: headlamp-ing
  namespace: headlamp
spec:
  rules:
    - host: my-host.org
      http:
        paths:
          - backend:
              serviceName: headlamp
              servicePort: 80
            path: /headlamp
            pathType: ImplementationSpecific
tls:
    - hosts:
        - my-host.org.tls
      secretName: headlamp-ngx

DEX config:
staticClients:
- id: oidc-auth-client
  name: oidc-auth-client
  redirectURIs:
  - https://my-host.org/headlamp/oidc-callback

4. **Error**: [describe the error that was triggered]

**Expected behavior**

Reachable callback URL (e.g. **https://YOUR_URL/headlamp/oidc-callback)** to Dex’s staticClient.redirectURIs

**Additional information**

Header after pressed "SIGN-IN" button

Request URL: https://oauth.my-host.org/dex/auth?client_id=oidc-auth-client&redirect_uri=https%3A%2F%2Fmy-host.org%2Foidc-callback&response_type=code&scope=openid+profile+email+groups&state=main

**Comment by joaquimrocha** [comment]
Thanks @zukko78 . We'll look into it.

**Comment by zukko78** [comment]
Hi folks!

Any update on this issue?

**Comment by joaquimrocha** [comment]
Hi @zukko78 ,

I think this [patch](https://github.com/kinvolk/headlamp/pull/239) fixes it. We need to test it though, but I will try to get this done ASAP (surely before the end of the week).
