### ISSUE TITLE
403 when trying to access resource

### ISSUE THREAD

**Issue by lunchboxav** [kinvolk/headlamp#29]
Hi,

I'm trying to run Headlamp in my local minikube cluster. This is my first time doing so. However, I can't get the resources in the dashboard, eventhough I'm using the default serviceaccount token. I verify that I can use this token to access API, e.g.

```
kubectl --token=$TOKEN get pods
```

gives me the list of pods running on my minikube.

In the browser, I can see that I have the following 403 error when opening the cluster page, e.g. `http://localhost:3000/c/minikube`

```
apiProxy.ts:48 GET http://localhost:4654/clusters/minikube/apis/metrics.k8s.io/v1beta1/nodes 403 (Forbidden)
request @ apiProxy.ts:48
getMetrics @ api.ts:178
index.js:1 No metrics {err: Error: Api request error: Forbidden - nodes.metrics.k8s.io is forbidden: User "system:anonymous" ca…, url: "/apis/metrics.k8s.io/v1beta1/nodes"}
```

So my question is, is there any additional step that I should do to test Headlamp, either in minikube or other running k8 cluster?

Thank you :)

**Comment by joaquimrocha** [comment]
Hi @lunchboxav . We've been using Headlamp with the metrics server installed. We will make this optional in the future but for now you'd need to install the metrics server for it to work.
There has been a lot of changes recently, so be sure to try the latest master.

**Comment by joaquimrocha** [comment]
Ah, looking closely again, maybe you'd need to ensure that you do have access to the metrics if you have the metrics server installed.

**Comment by joaquimrocha** [comment]
Please take a look at the instructions on how to get the metrics server running on Minikube. This has been tested last week.
https://kinvolk.io/docs/headlamp/0.1/installation/metrics-server/
