### ISSUE TITLE
[RFE] Fix Helm chart repository

### ISSUE THREAD

**Issue by FlipEnergy** [kinvolk/headlamp#291]
## Description

Thanks for the new chart! However I noticed the chart Repository is not available yet. 
`helm repo add headlamp https://kinvolk.github.io/headlamp/` reports a 404.

As a bonus, it would be nice to add this Helm Repo to https://artifacthub.io/.

## Impact

Folks can pull your Helm chart directly without needing to download from Github releases.

## Environment and steps to reproduce

1. run `helm repo add headlamp https://kinvolk.github.io/headlamp/`  and see that it returns a 404
2. or simply go to https://kinvolk.github.io/headlamp/ and see 404

## Expected behavior

The repository is successfully added when run `helm repo add headlamp https://kinvolk.github.io/headlamp/` and a subsequent command of `helm show chart headlamp/headlamp` returns the chart.yaml

**Comment by joaquimrocha** [comment]
Hi @FlipEnergy . Thanks for reporting!

We hadn't yet published the github page for holding the repo. Can you double check it now?

**Comment by FlipEnergy** [comment]
Looks like I can add the Repo now but the chart itself is missing. I took a look at the gh-pages branch and it seems I'm right.

```
$ helm repo add headlamp https://kinvolk.github.io/headlamp/
"headlamp" has been added to your repositories
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "headlamp" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm search repo headlamp
No results found
[dennis@DENNIS-DESKTOP ~]$ helm show chart headlamp/headlamp
Error: failed to download "headlamp/headlamp" (hint: running `helm repo update` may help)
```

**Comment by joaquimrocha** [comment]
Thanks. We'll look into it.

**Comment by joaquimrocha** [comment]
I hadn't noticed the actual log for the action (or I'd realize it'd not have published anything before). Should be fine now.
Thanks!
