### ISSUE TITLE
Import module types to plugins

### ISSUE THREAD

**Issue by ashu8912** [kinvolk/headlamp#324]
## Current situation

Right now all the modules we attach to pluginLib are passed as type any because of which there is no way we can use all the typescript benefits from those modules such as strict types, hinting on objects, etc

We should have concrete types on modules that are present on the pluginLib

**Comment by illume** [comment]
Module federation https://webpack.js.org/concepts/module-federation/ might be worth looking into soon. Just looked into this, and webpack 5 is already merged into create react app, but module federation support is stalled in a PR ready to go. However, it's apparently approved to land in create-react-app 5.1 (not 5.0). Maybe we can use webpack 5 directly and have headlamp-plugin serve the required modules somehow (but I didn't look into this at all).

Copying type definitions might be another high-ish maintenance but lofi method to get type definitions.

Another option for the short term is to develop the plugin inside headlamp to start with, and then change the `import` statements to `require` when you're ready to publish.

Perhaps looking into if using peer dependencies somehow again might be worthwhile as well.
