### ISSUE TITLE
Prettify the JSON and YAML views

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/headlamp#34]
We should highlight the JSON and YAML data in the several views that show it. E.g. https://www.prettifier.net/json/

**Acceptance Criteria:**
-  [x] The JSON data is highlighted
-  [ ] The YAML data is highlighted

**Comment by ashu8912** [comment]
fixes #38

**Comment by ashu8912** [comment]
@joaquimrocha this can be closed now

**Comment by joaquimrocha** [comment]
We can close it. But we should assign the dark theme everywhere because of that issues with the singleton editor theme.
