### ISSUE TITLE
White page when reloading the page

### ISSUE THREAD

**Issue by Kerwood** [kinvolk/headlamp#345]
## Description
After installing Headlamp in Kubernetes and logging in in with the service account token, you will end up on `https://your-url.org/c/main`. If you then reload the page or any other sub page in head lamp, you just get a white page. Or if you click a direct link to eg. Workloads -> Pods.

The browser console will show below error when reloading.
![image](https://user-images.githubusercontent.com/4029521/139261563-ba98dd0b-83b1-44a7-8790-21a9544581f0.png)

Tested on Chrome + Windows and Fedora + Firefox.

## Environment and steps to reproduce
Deploy the `ghcr.io/kinvolk/headlamp:v0.5.2` image kubernetes and setup a service account, [like in the docs](https://kinvolk.io/docs/headlamp/latest/installation/).

Get the service account token.

Port forward from the Headlamp service to localhost.
```
kubectl -n kube-system port-forward svc/headlamp 8080:80
```

**Comment by ashu8912** [comment]
thanks @Kerwood for reporting this, I am taking a look into this and will get back to you soon

**Comment by joaquimrocha** [comment]
@Kerwood , thanks for reporting this. May I ask which K8s flavor you are using?

**Comment by Kerwood** [comment]
Its a self hosted on-prem cluster. I'll just quickly try it in a GKE cluster to see if I get the same result.

**Comment by illume** [comment]
Do you have the JS console "preserve log" option enabled? 
It could be the page is being reloaded and wiping out other relevant errors.
`(console tab -> settings icon -> "preserve log")`

**Comment by Kerwood** [comment]
Just tested it on a fresh GKE install and its the same result.
I enabled persist logs and this is what i got.
![image](https://user-images.githubusercontent.com/4029521/140929730-e4713086-2d23-4225-aab3-d7215f84a2a0.png)

I forgot to mention that I actually use Pomerium i front of Headlamp. I will try and test with out.

**Comment by Kerwood** [comment]
Just tested it without Pomerium, same result.

**Comment by ashu8912** [comment]
Hello @Kerwood I tested the latest headlamp image on GKE and I am able to reproduce the issue you are facing,
We are still looking into the root cause of it as soon as we get anything will revert back to you.

**Comment by Kerwood** [comment]
Thank you.

**Comment by joaquimrocha** [comment]
@Kerwood , This is fixed in `main`. We will have a release next so it gets officially fixed. Thanks again for reporting.

**Comment by Kerwood** [comment]
@joaquimrocha My pleasure. Thank you for fast delivery :+1:
