### ISSUE TITLE
Gracefully handle errors when the metrics server is not installed

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/headlamp#40]
The metrics server shouldn't be a requirement for running Headlamp, but currently the code just assumes we have metrics server installed.

We should make sure that if the metrics server is not installed then we simply don't show the charts/info we generate from the metrics, and instead we should display a message suggesting to install the metrics server. This message should be non-intrusive and small at the moment (later we can add a link to how to install it, etc.).

**Comment by ashu8912** [comment]
fixes #41
