### ISSUE TITLE
[Windows] Terminal does nothing

### ISSUE THREAD

**Issue by splitice** [kinvolk/headlamp#414]
![Headlamp_2022-02-02_10-50-22](https://user-images.githubusercontent.com/468579/152070969-be55836d-e790-49ab-93e5-0b6bc1c065df.png)

No XHR, no connection, nothing relevant in the console.

**Comment by joaquimrocha** [comment]
Hi @splitice , thanks for reporting.
The terminal sometimes takes a while to connect, but should end up in a prompt or an error message in that web "console". I've recently noticed it doesn't focus the console automatically though.

I see a sharp sign in the terminal in your screenshot, does it not work (allow you to type and send commands) if you focus (click or tab navigate) the console area?

If it does not work at all, then it would be useful if you could share more details about your k8s environment: what kind of container you tried to exec into for example.

**Comment by splitice** [comment]
Ah, my bad. I see it's starting with /bin/sh which only gives a `#`. This combined with lthe lack of focus (likely for the same reason you have seen it) lead me to beleive that `#` was just some kind of status indication.

**Comment by splitice** [comment]
How is the default shell being detirmined anyway?

**Comment by joaquimrocha** [comment]
> How is the default shell being detirmined anyway?

It's just trying to run `sh`. Probably we should extend that to try more shell commands...

**Comment by joaquimrocha** [comment]
> Ah, my bad. I see it's starting with `/bin/sh` which only gives a `#`. This combined with lthe lack of focus (likely for the same reason you have seen it) lead me to beleive that `#` was just some kind of status indication.

No worries. I have opened an issue (#416) to have the focus by default and make it clearer for the user that the terminal is connected.
