### ISSUE TITLE
[RFE] Ensure routes are rendered only after the plugins are loaded

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/headlamp#454]
## Current situation

Plugins may define or override routes. If they override an existing route but the user navigates to that route before the plugins are loaded, they may still see the default route components being rendered until the plugin is loaded and replaces it.

## Impact

It prevents plugins from providing a stable UX for the user.

## Ideal future situation

We only render routes after all plugins are rendered, which allows for the plugins to fully replace routes.

**Comment by ashu8912** [comment]
@joaquimrocha we could have a loading page which says something like 'Getting Everything Ready' till the plugin loads because not loading the routes would mean users wouldn't be able to interact with the app and we need a loader or something to depict that we are preparing things for you. WDYT??

**Comment by joaquimrocha** [comment]
We need something like that. Maybe just a spinner with a "loading..." tooltip is enough. We need to make sure that we set a maximum time allowed for the plugins to load, and if they are not loaded in that time, we should proceed without waiting (so you would see the current delay in rendering that we see now sometimes). I hope 1/4 sec is enough for this timeout...
