### ISSUE TITLE
[Desktop - MacOS] Plugin dist sporadically freezes in cache

### ISSUE THREAD

**Issue by andrii-batiuk** [kinvolk/headlamp#473]
## Description

Occasionally plugin dist 'freezes' in Electron cache of Headlamp.

## Impact

Bad development experience, inability to see the changes in Headlamp runtime.

## Environment and steps to reproduce

1. **Set-up**: Headlamp
2. **Task**: Observe the changes in runtime made to the plugin code
3. **Action(s)**:
a. Stop the running server
b. Make change to the code, for example change `console.log('headlamp-myplugin initialized');` to `console.log('headlamp-myplugin initialized123123');`
c. Run `rm -rf $HOME/Library/Application\ Support/Headlamp/plugins/headlamp-myplugin/main.js; rm -rf dist/`
d. Run npm start
e. See that change isn't displayed in Headlamp, i.e. in the console is logged `headlamp-myplugin initialized `instead of `headlamp-myplugin initialized123123`
4. **Error**: Can't observe the changes even during hot reload

## Workaround
Wiping the Electron cache of the Headlamp solved the issue:
`rm -rf $HOME/Library/Application\ Support/Headlamp/`

**Comment by joaquimrocha** [comment]
This is an important one. We need to prioritize it.
Thanks for reporting, @andrii-batiuk .

**Comment by andrii-batiuk** [comment]
Also, forgot to add that I made grep for the change (initialized123123) in the main.js both in `/dist` and in `$HOME/Library/Application\ Support/Headlamp/plugins/headlamp-myplugin/` to ensure that changes are in place - and they were in those files.

**Comment by illume** [comment]
@andrii-batiuk were there any errors logged in the `npm start` terminal?

**Comment by andrii-batiuk** [comment]
@illume `npm start` logged in errors.  Local dist folder I wiped just to ensure that no extra copies of plugin bundle left.
I downloaded Headlamp as a DMG.

**Comment by joaquimrocha** [comment]
@andrii-batiuk , you can find a build in https://github.com/kinvolk/headlamp/actions/runs/2101128126

**Comment by andrii-batiuk** [comment]
Well, I just installed the new build and discovered that `CustomResource` is absent in `pluginLib.K8s.ResourceClasses`. 

I've got an error `api.ts:13 Uncaught TypeError: K8s.ResourceClasses.CustomResource is not a constructor`.

I am heavily using the `new K8s.CustomResource(...);`.

Is that some breaking change going to be introduced permanently?

**Comment by andrii-batiuk** [comment]
Right now I am observing another issue - suddenly Headlamp stopped showing my plugin at all. While I have no build errors and plugin is located in $HOME/Library/Application\ Support/Headlamp/plugins folder.

**Comment by illume** [comment]
Hi. 

sorry, this was replaced by makeCustomResourceClass 

- https://github.com/kinvolk/headlamp/pull/460
- [example custom-resource plugin](https://gist.github.com/ashu8912/fa8c981f05b947d8d45b72e3d564e970)

**Comment by joaquimrocha** [comment]
@andrii-batiuk , the fix is also now in Headlamp 0.8.0. Once you verify if this is the fix, we can close this issue.

**Comment by andrii-batiuk** [comment]
@joaquimrocha for a couple of days of usage of 0.8 version - the issue is not observed, so far. I'm doing Headlamp plugin development with my common behavioural patterns (like using hibernation, not shutting down npm serve or Headlamp etc.).

**Comment by illume** [comment]
Cool. Let's close this.

Of course we can have another look if the issue pops back up :)
