### ISSUE TITLE
The name of server.exe might be conflicted with other process

### ISSUE THREAD

**Issue by lijianzhi01** [kinvolk/headlamp#487]
## Description

In my computer, other process called server.exe is running, headlamp failed to start. Please replace server.exe to headlamp_server.exe or some other name.

**Comment by joaquimrocha** [comment]
I have been wanting to rename the executable to something more specific for a while. I didn't know there would be problems with name clashing like this though.

If we do, we should make sure we have a symlink in the container image, so older deployments can still call `/.../server ...`, or a wrapper script to be able to print a deprecation notice.
