### ISSUE TITLE
[Plugin] PNG are corrupted with url-loader

### ISSUE THREAD

**Issue by lijianzhi01** [kinvolk/headlamp#489]
## Description

I import a png into my plugin. After png compiled and saved to Config folder, it cannot be opened. So, the walk around is temporarily removing url-loader. I think left side is compiled by url-loader. The right side is compiled by file-loader. The png from left side has only 80 btyes.

![image](https://user-images.githubusercontent.com/13809749/162659354-8598c86a-28f9-4292-93be-3d95a49a3172.png)

**Comment by illume** [comment]
I haven't looked into this yet, but here are some workarounds...

- Use SVG or an icon. Depending on what the image is of, of course.
- Base64 encode and inline `<img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />`
