### ISSUE TITLE
[BUG] Headlamp unable to process KUBECONFIG environment correctly

### ISSUE THREAD

**Issue by fondoger** [kinvolk/headlamp#514]
According to [Kubernetes Docs](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#windows-powershell),

> The KUBECONFIG environment variable is **a list of paths** to configuration files. The list is colon-delimited for Linux and Mac, and semicolon-delimited for Windows. If you have a KUBECONFIG environment variable, familiarize yourself with the configuration files in the list.

However, **headlamp** assumes `KUBECONFIG` is a path to a single file. https://github.com/kinvolk/headlamp/blob/main/app/electron/main.ts#L51

Headlamp will crash if `KUBECONFIG` is a list of comma-separated file path string.

**Comment by joaquimrocha** [comment]
Oh! Very good catch @fondoger . We will raise the priority on this one.

**Comment by joaquimrocha** [comment]
@yolossn , Maybe you can look into this one?
