### ISSUE TITLE
[RFE] Log Viewer show timestamps & previous container logs

### ISSUE THREAD

**Issue by fondoger** [kinvolk/headlamp#526]
https://jamesdefabia.github.io/docs/user-guide/kubectl/kubectl_logs/

eg: `kubectl logs -p <pod_name>`
eg: `kubectl logs --timestamps <pod_name>`

**Comment by joaquimrocha** [comment]
@fondoger Do you mean we should make sure that the timestamps are being shown in the log viewer?
