### ISSUE TITLE
Import ConditionsTable

### ISSUE THREAD

**Issue by Aryamn** [kinvolk/headlamp#564]
How can I import ```ConditionsTable``` component  defined [here ](https://github.com/kinvolk/headlamp/blob/a9994036a47d4e23b581442dd751395cf68dff2a/frontend/src/components/common/Resource/Resource.tsx#L340)into my plugin.

**Comment by joaquimrocha** [comment]
Hi @Aryamn . The Resource module was not being exposed to plugins. We've just fixed this in the PR #567 .
We'll have a bug release next week which will publish these changes. Thanks!

**Comment by joaquimrocha** [comment]
This is now fixed and published in Headlamp 0.10.1. Thanks for reporting.
