### ISSUE TITLE
Configure golangci-lint for the project

### ISSUE THREAD

**Issue by knrt10** [kinvolk/headlamp#57]
Like we have in lokomotive. You can add this for writing a clean go code. I think currently, only 2 linters are used and more should be enabled. For more information https://github.com/kinvolk/lokomotive/blob/master/.golangci.yml

What do you think @joaquimrocha @ashu8912?

**Comment by joaquimrocha** [comment]
@knrt10 This should be unified somehow. I see that the L8e lint file has some particular stuff there that's no useful on every project, so I will think about how we can integrate this in a company-wide way.

**Comment by joaquimrocha** [comment]
We now have a comprehensive set of linter rules, taken from the Lokomotive project.
