### ISSUE TITLE
`kinvolk/headlamp` image is no longer available

### ISSUE THREAD

**Issue by spowelljr** [kinvolk/headlamp#642]
The `headlamp` addon is broken on [minikube](https://github.com/kubernetes/minikube). The image `kinvolk/headlamp` is no longer available as evident on https://hub.docker.com/search?q=kinvolk%2Fheadlamp.

As well as:
```
docker pull kinvolk/headlamp
Using default tag: latest
Error response from daemon: pull access denied for kinvolk/headlamp, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by ashu8912** [comment]
Hello @spowelljr  i think headlamp image is hosted on ghcr.io/kinvolk/headlamp and not on docker.io and the addon also uses ghcr.io/kinvolk/headlamp. 
Can you give us more details about the addon failing??
ccing @yolossn for follow up
