### ISSUE TITLE
WIP: noCluster is confusing

### ISSUE THREAD

**Issue by illume** [kinvolk/headlamp#657]
## Description

noCluster is confusing people.

## Impact

[ 1 sentence detailing the impact this bug is creating for you ]

## Environment and steps to reproduce

1. **Set-up**: [ describe the environment Flatcar/Lokomotive/Nebraska etc was running in when encountering the bug; Platform etc. ]
2. **Task**: [ describe the task performing when encountering the bug ]
3. **Action(s)**: [ sequence of actions that triggered the bug, see example below ]
  a. [ requested the start of a new pod or container ]
  b. [ container image downloaded ]
4. **Error**: [describe the error that was triggered]

## Expected behavior

[ describe what you expected to happen at 4. above but instead got an error ]

## Additional information

Please add any information here that does not fit the above format.

**Comment by joaquimrocha** [comment]
This is already fixed in #664 .
