### ISSUE TITLE
[RFE] social card for github

### ISSUE THREAD

**Issue by illume** [kinvolk/headlamp#689]
The [Social image](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview) is used on social so it shows a nice headlamp-specific-image rather than the github one.

Because more prettier, and more better engagement. So there is a headlamp specific preview image.

For inspo, see examples of social cards at https://github.com/explore The [Social image docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview) has more info like pixel size of the image.

**Comment by tsompura** [comment]
Please try these graphics. If needed, we can add a tagline below the logo.

<img width="1280" alt="headlamp-01" src="https://user-images.githubusercontent.com/61687470/194563675-8822bf7c-2879-4ae8-a859-f9e677fe5fe3.png">
<img width="1280" alt="headlamp-02" src="https://user-images.githubusercontent.com/61687470/194563685-43f899f0-fdfb-40a2-b4be-7280259f6d51.png">

**Comment by joaquimrocha** [comment]
@tsompura Thanks! Can you add "The extensible UI for Kubernetes" as a tagline?

**Comment by tsompura** [comment]
@joaquimrocha Updated with tagline. 
<img width="1280" alt="headlamp-01" src="https://user-images.githubusercontent.com/61687470/194857507-91fd998c-c64f-49e9-81ca-c3fda01b66c2.png">
<img width="1280" alt="headlamp-02" src="https://user-images.githubusercontent.com/61687470/194857522-09ba5ab6-4fc5-4441-9c6d-6cee6d71916b.png">

**Comment by blixtra** [comment]
The most recent green one is cool.

**Comment by joaquimrocha** [comment]
Thanks @tsompura . I have applied the one Chris picked. Great job.
