### ISSUE TITLE
Viewport jump when clearing filter search

### ISSUE THREAD

**Issue by callmevladik** [kinvolk/headlamp#699]
## Description

Screen viewport bounces when user clears his filter search input

## Impact

It's uncomfortable for user to interact with search field

## Environment and steps to reproduce

Navigate to Search field when there are 10+ items on the list
Enter value
Clear the field

## Expected behavior

Search field stays on the same place and nothing bounces

**Comment by joaquimrocha** [comment]
I guess this is different from https://github.com/kinvolk/headlamp/issues/593, but let's check out exactly what this means.
