### ISSUE TITLE
[Improve routing] App loses namespace URL param when changing resource type page

### ISSUE THREAD

**Issue by callmevladik** [kinvolk/headlamp#739]
## Description

If user goes to list page for example Services and chooses namespace then url will get a param like this ?namespace=my-test-namespace-name, after this if user goes to another list page for example Ingresses,  filter still stays with chosen namespace, but url doesn't anymore, so if user reloads the page it will lose chosen namespace 

## Impact

Uncomfortable user experience

## Environment and steps to reproduce

1. Go to Services resource page
2. Choose namespace
3. Go to Ingresses resource page
4. Reload page

## Expected behavior

url doesn't lose its namespace param after reloading page

**Comment by joaquimrocha** [comment]
Thanks @callmevladik .
That's a good point. We have #21 since a while which is related to being able to reload views and seeing the same state.
For the namespaces maybe this is even more important, so we'll look into it.

**Comment by joaquimrocha** [comment]
This is fixed now.

**Comment by callmevladik** [comment]
I wouldn't say it is fixed since I still see the problem, but I can be wrong.

Please, try to follow these steps:
1. Open Services page
2. Select namespace 
3. Go to specific Service resource page
4. Go back

After these steps you should see that your selected namespace disappeared from URL and the filter.

**Comment by illume** [comment]
I just tried it too. It appears fixed now. (unless I'm doing something wrong)

**Comment by callmevladik** [comment]
Yeah, maybe I didn't catch up the latest changes. Thank you!

**Comment by illume** [comment]
Ok, that's good! Thanks @callmevladik
