### ISSUE TITLE
[RFE] Enable extend getToken in plugin

### ISSUE THREAD

**Issue by lijianzhi01** [kinvolk/headlamp#761]
## Current situation

Each k8s requests require a token read from localstorage through getToken().

## Impact

If we cannot extend getToken, access token will be expired in about 30 minutes. And there is no appropriate timing to trigger extend expiration function. 

## Ideal future situation

In a scenario, access token should be fetched for extending expiration by fetching Restful API. 

## Implementation options

[ Optional: please provide one or more options for implementing the feature requested ]

## Additional information

[ Please Add any information that does not fit into any of the above sections here ]

**Comment by lijianzhi01** [comment]
Link to https://github.com/kinvolk/headlamp/issues/749

**Comment by joaquimrocha** [comment]
Closing in favor of #749
