### ISSUE TITLE
[RFE] Allow to search by involved object type in Events table

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/headlamp#769]
## Current situation

We show an events' table in the cluster overview which we can search but not by the involved object's type, and this would be a good way to filter out events by the user.

## Ideal future situation

Typing replicaset or pod would filter the table to only show the ReplicaSet or Pod objects, respectively.

**Comment by nitoC** [comment]
please assign this to me.

**Comment by joaquimrocha** [comment]
Hi @nitoC . Sorry I missed your message. We are happy to have you contribute to Headlamp.
This task is already under development in our team but I encourage you to look for another one you may be motivated to tackle.

If you want a more direct way to chat with the team, you can find us in the headlamp channel of the Kubernetes Slack: https://kubernetes.slack.com/messages/headlamp
