### ISSUE TITLE
Back Button broken for Roles and Role Bindings View 

### ISSUE THREAD

**Issue by ashu8912** [kinvolk/headlamp#77]
Steps to Reproduce the above issue in Roles View:
1. Go to Roles view
2. Use the table paginator and press the next arrow button on it
3. Now Click on any role name from the list
4. In the Role Detail View Press the Back Button and Boom you will be redirected to chooser page

Steps to Reproduce the above issue in RoleBindings View
1. Go to RoleBindings View
2. Click on any Name from the list
3. On the RoleBindings Detail View Now Press Back and Boom You will be redirected to chooser page

**Comment by joaquimrocha** [comment]
Fixed this week by #78 .
