### ISSUE TITLE
[useList/useApiGet hooks] [streamResult/streamResults functions] Callback fires twice on same resource/s

### ISSUE THREAD

**Issue by callmevladik** [kinvolk/headlamp#783]
## Description

When we use useList or useApiGet hooks, we use streamResult/streamResults functions under the hood which get success callback as a parameter.
StreamResult function makes an initial request and fires success callback on received data and then creates a socket which immediately gets a first message with the same resource and again fires success callback  which makes our views render twice on the same data.
I think stream functions could compare resourceVersion of the object it gets on first request and the object it gets from first message and fire the callback only if it gets a new object.
Some similar logic described in streamResults function in switch construction in MODIFIED case.

## Impact

Performance

## Expected behavior

Fire a success callback only when new data is received

**Comment by joaquimrocha** [comment]
@callmevladik , I made this simple change in https://github.com/kinvolk/headlamp/pull/786 which I think accomplishes what you need in `useGet`. We will eventually review the whole API connection workflow in Headlamp, but that may require more time.

Can you test the PR and check whether it prevents unnecessary re-renders for you?

**Comment by callmevladik** [comment]
@joaquimrocha hmm, i'm not sure, but when I console.log the resource in state it shows twice on first render

**Comment by joaquimrocha** [comment]
That may be normal. Can you check if it changes from the main branch for you?
