### ISSUE TITLE
Create a Helm chart

### ISSUE THREAD

**Issue by johananl** [kinvolk/headlamp#82]
Helm is used by a large portion of the k8s community for managing workloads. We probably want to have an official chart for Headlamp.

**Comment by jkroepke** [comment]
@johananl Did you need help here? I could provide one by creating a pr if interested.

**Comment by joaquimrocha** [comment]
@jkroepke Hey! Sorry we didn't reply before!
Yes, any PRs are welcome. It'd be great to get your contributions.

**Comment by joaquimrocha** [comment]
This is done.
