### ISSUE TITLE
Decide on an approach for authentication in hosted mode

### ISSUE THREAD

**Issue by johananl** [kinvolk/headlamp#86]
When deploying Headlamp on a cluster, we may want to consider supporting auth using a service account.

Pros:

- It Just Works (TM) - the user doesn't have to figure out what a "token" is and how to get one.

Cons:

- Compromising the Headlamp pod grants access to the cluster at the same permission level as the service account.
- No per-user authentication, so harder to do things like auditing.

**Comment by joaquimrocha** [comment]
For what kind of use-case is this wanted?
We have OIDC landing very soon (solving the token complexity thing), and we also support client certificates (though I guess that may not be suitable if we're talking about just accessing a URL).

Still if it makes sense we should consider (and we already have a more solid auth option, so users can always pick when deploying).

**Comment by johananl** [comment]
I've reread my description and this doesn't make sense to me. My concern was that when Headlamp is deployed **on a cluster** we have to send the user to look for tokens. I wanted to improve the UX there, but I guess I forgot that even if Headlamp authenticates itself against the API server using a service account, the **user** still needs to authenticate to Headlamp.

Anyway, OIDC sounds good to me. I'll close this.

**Comment by olivierpilotte** [comment]
I've just deployed Headlamp on my cluster and I can't find what is the token I need to use to authenticate. I've searched the documentation, the repo. Can you guys point me in the right direction? It's not clear at all.
