### ISSUE TITLE
Exec to a pod results with "Failed to run cmd.exe" after few minutes

### ISSUE THREAD

**Issue by eresgie** [kinvolk/headlamp#866]
## Description

When trying to exec to any pod everything goes smoothly, but after almost 3 minutes "Failed to run cmd.exe" message appears making further terminal use unusable.

## Impact

User cannot use terminal longer than few minutes.

## Environment and steps to reproduce

To better understand a problem, small video file is attached with all required steps.

[https://youtu.be/_fMO1Ha9Qoc](https://youtu.be/_fMO1Ha9Qoc)

## Expected behavior

Exec into pod shouldn’t result in unusable terminal after a few minutes.

## Additional information

Tested on Headlamp version 0.14.0 using Google Chrome on Mac machine.

**Comment by joaquimrocha** [comment]
@eresgie , Thanks for the detailed report and the helper video. This makes it very clear what the failed UX is. We'll look into this.
Can you in the meanwhile confirm that the container you successfully exec into is a Linux one (i.e. not using cmd.exe)?

**Comment by eresgie** [comment]
@joaquimrocha Thank you, but I'm using Web UI and server version deployed on Kubernetes, so it could be hard for me to test it.

**Comment by WeSTManCoder** [comment]
Check the parameters on all balancers with ingress
proxy_read_timeout 3600;
proxy_send_timeout 3600;
